version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: expanders_mysql
    environment:
      MYSQL_ROOT_PASSWORD: othmanpassword
      MYSQL_DATABASE: expanders360
      MYSQL_USER: othman
      MYSQL_PASSWORD: othmanpassword
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: expanders_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: expanders360_docs
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: expanders_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongo_data:
  redis_data:
